# Generated by Django 5.1.15 on 2026-10-08 05:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Nomi"),
                ),
            ],
            options={
                "verbose_name": "Bo'lim",
                "verbose_name_plural": "Bo'limlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="F.I.Sh.")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Lavozim"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Ishga kirgan sana",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tug'ilgan sana"
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="Oylik maosh",
                    ),
                ),
                (
                    "work_start",
                    models.TimeField(
                        default=datetime.time(9, 0), verbose_name="Ish boshlanishi"
                    ),
                ),
                (
                    "work_end",
                    models.TimeField(
                        default=datetime.time(18, 0), verbose_name="Ish tugashi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ishlayapti"),
                            ("dismissed", "Ishdan ketgan"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ishdan ketgan sana"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.department",
                        verbose_name="Bo'lim",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="CRM foydalanuvchisi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xodim",
                "verbose_name_plural": "Xodimlar",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vacation", "Mehnat ta'tili"),
                            ("sick", "Kasallik"),
                            ("unpaid", "O'z hisobidan"),
                            ("other", "Boshqa"),
                        ],
                        default="vacation",
                        max_length=10,
                        verbose_name="Turi",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Boshlanishi")),
                ("end_date", models.DateField(verbose_name="Tugashi")),
                ("reason", models.TextField(blank=True, verbose_name="Sabab")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ko'rib chiqilmoqda"),
                            ("approved", "Tasdiqlandi"),
                            ("rejected", "Rad etildi"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Holat",
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="hr.employee",
                        verbose_name="Xodim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ta'til so'rovi",
                "verbose_name_plural": "Ta'til so'rovlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="Sana",
                    ),
                ),
                (
                    "check_in",
                    models.DateTimeField(blank=True, null=True, verbose_name="Keldi"),
                ),
                (
                    "check_out",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ketdi"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Izoh"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Davomat",
                "verbose_name_plural": "Davomat",
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
