# Generated by Django 5.1.15 on 2026-10-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sip_extension",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Asterisk'dagi operator ichki raqami, masalan 101",
                max_length=20,
                verbose_name="Ichki raqam (SIP)",
            ),
        ),
    ]
