# Generated by Django 5.1.15 on 2026-10-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_sip_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
