# Generated by Django 5.1.15 on 2026-10-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_scope",
            field=models.CharField(
                choices=[
                    ("all", "Barcha ma'lumotlar"),
                    ("own", "Faqat o'ziga tegishli"),
                ],
                default="own",
                max_length=5,
                verbose_name="Ma'lumotlar doirasi",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_access",
            field=models.BooleanField(default=False, verbose_name="To'liq dostup"),
        ),
        migrations.AddField(
            model_name="user",
            name="modules",
            field=models.JSONField(blank=True, default=list, verbose_name="Modullar"),
        ),
    ]


def set_access_from_role(apps, schema_editor):
    """Mavjud foydalanuvchilar avvalgi huquqlarini saqlaydi."""
    User = apps.get_model("accounts", "User")
    operator = ["dashboard", "leads", "phone_app"]
    for user in User.objects.all():
        if user.is_superuser or user.role in ("admin", "manager"):
            user.full_access, user.modules, user.data_scope = True, [], "all"
        elif user.role == "service":
            user.full_access, user.modules, user.data_scope = False, ["orders"], "own"
        else:
            user.full_access, user.modules, user.data_scope = False, operator, "own"
        user.save(update_fields=["full_access", "modules", "data_scope"])


Migration.operations.append(migrations.RunPython(set_access_from_role, migrations.RunPython.noop))
