# Generated by Django 5.1.15 on 2026-10-08 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nomi")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Narxi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="F.I.Sh.")),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Telefon"
                    ),
                ),
                (
                    "extra_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Qo'shimcha telefon"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Hudud"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Sayt"),
                            ("instagram", "Instagram"),
                            ("telegram", "Telegram"),
                            ("facebook", "Facebook"),
                            ("call", "Kiruvchi qo'ng'iroq"),
                            ("referral", "Tavsiya"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Manba",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("in_progress", "Ishlanmoqda"),
                            ("callback", "Qayta qo'ng'iroq"),
                            ("interested", "Qiziqdi"),
                            ("won", "Sotuv"),
                            ("lost", "Rad etildi"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "next_call_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Keyingi qo'ng'iroq"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "operator"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lid",
                "verbose_name_plural": "Lidlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("answered", "Gaplashildi"),
                            ("no_answer", "Javob bermadi"),
                            ("busy", "Band"),
                            ("wrong_number", "Noto'g'ri raqam"),
                            ("callback", "Qayta qo'ng'iroq so'radi"),
                        ],
                        max_length=20,
                        verbose_name="Natija",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vaqt"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operator",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qo'ng'iroq",
                "verbose_name_plural": "Qo'ng'iroqlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Summa"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sana"),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="crm.lead",
                        verbose_name="Lid",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operator",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="crm.service",
                        verbose_name="Xizmat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sotuv",
                "verbose_name_plural": "Sotuvlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("in_progress", "Bajarilmoqda"),
                            ("done", "Bajarildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejalashtirilgan vaqt"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Manzil"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bajarilgan vaqt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "service"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mas'ul xodim",
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="crm.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat buyurtmasi",
                "verbose_name_plural": "Xizmat buyurtmalari",
                "ordering": ["-created_at"],
            },
        ),
    ]
