# Generated by Django 5.1.15 on 2026-10-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="phone_norm",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=20
            ),
        ),
    ]


def fill_phone_norm(apps, schema_editor):
    from telephony.utils import normalize_phone

    Lead = apps.get_model("crm", "Lead")
    for lead in Lead.objects.only("id", "phone").iterator():
        Lead.objects.filter(pk=lead.pk).update(phone_norm=normalize_phone(lead.phone))


Migration.operations.append(migrations.RunPython(fill_phone_norm, migrations.RunPython.noop))
