# Generated by Django 5.1.15 on 2026-10-08 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_lead_phone_norm"),
        ("telephony", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="phone_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="telephony.phonecall",
            ),
        ),
    ]
