# Generated by Django 5.1.15 on 2026-10-08 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("callback", "Qo'ng'iroq vaqti"),
                            ("lead", "Yangi lid"),
                            ("order", "Xizmat buyurtmasi"),
                            ("missed", "O'tkazib yuborilgan qo'ng'iroq"),
                            ("update", "Yangilanish"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(blank=True, max_length=500)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("key", models.CharField(blank=True, max_length=120)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("key", ""), _negated=True),
                        fields=("user", "key"),
                        name="uniq_notification_key",
                    )
                ],
            },
        ),
    ]
