# Generated by Django 5.1.15 on 2026-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("callback", "Qo'ng'iroq vaqti"),
                    ("lead", "Yangi lid"),
                    ("order", "Xizmat buyurtmasi"),
                    ("missed", "O'tkazib yuborilgan qo'ng'iroq"),
                    ("update", "Yangilanish"),
                    ("leave", "Ta'til"),
                ],
                max_length=20,
            ),
        ),
    ]
