# Generated by Django 5.1.15 on 2026-10-08 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_lead_phone_norm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uniqueid",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Kiruvchi"), ("out", "Chiquvchi")],
                        max_length=3,
                        verbose_name="Yo'nalish",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ringing", "Jiringlamoqda"),
                            ("answered", "Javob berildi"),
                            ("no_answer", "Javobsiz"),
                            ("busy", "Band"),
                            ("failed", "Xatolik"),
                        ],
                        db_index=True,
                        default="ringing",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                ("phone", models.CharField(max_length=32, verbose_name="Mijoz raqami")),
                (
                    "extension",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Ichki raqam"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Boshlangan"
                    ),
                ),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Davomiylik (s)"
                    ),
                ),
                (
                    "recording",
                    models.FileField(
                        blank=True,
                        upload_to="recordings/%Y/%m/",
                        verbose_name="Ovoz yozuvi",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(blank=True, verbose_name="Suhbat matni"),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_calls",
                        to="crm.lead",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telefon qo'ng'irog'i",
                "verbose_name_plural": "Telefon qo'ng'iroqlari",
                "ordering": ["-started_at"],
            },
        ),
    ]
