# Generated by Django 5.1.15 on 2026-10-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telephony", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecall",
            name="client_id",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="phonecall",
            name="source",
            field=models.CharField(
                choices=[
                    ("asterisk", "ATS"),
                    ("mobile", "Telefon ilovasi"),
                    ("manual", "Qo'lda yuklangan"),
                ],
                default="asterisk",
                max_length=10,
                verbose_name="Manba",
            ),
        ),
    ]
